### ISSUE TITLE
Too smart

### ISSUE THREAD

**Issue by NorteX-dev** [catcosmicice/catcosmicice#2]
He's too smart. This needs to be resolved asap.

**Comment by aryavsaigal** [comment]
Elimination is the key

**Comment by WeirderConcoctions** [comment]
Work on an app that makes a user dumber as he or she uses it

**Comment by cosmicle0** [comment]
wait what is this issue lol, i didn't even notice it being created...

**Comment by aryavsaigal** [comment]
the issue is that zeg is too smart and elimination is the key to ending his smartness

**Comment by cosmicle0** [comment]
> Work on an app that makes a user dumber as he or she uses it

uhm who are you? why have you been stalking me and some other guys? 🤔

**Comment by WeirderConcoctions** [comment]
> > Work on an app that makes a user dumber as he or she uses it
> 
> uhm who are you? why have you been stalking me and some other guys? 🤔

I know DARKDRAGON532 well

**Comment by cosmicle0** [comment]
> > > Work on an app that makes a user dumber as he or she uses it
> > 
> > 
> > uhm who are you? why have you been stalking me and some other guys? 🤔
> 
> I know DARKDRAGON532 well

but that doesn't change the fact that you're stalking his friends lol

**Comment by WeirderConcoctions** [comment]
> > > > Work on an app that makes a user dumber as he or she uses it
> > > 
> > > 
> > > uhm who are you? why have you been stalking me and some other guys? 🤔
> > 
> > 
> > I know DARKDRAGON532 well
> 
> but that doesn't change the fact that you're stalking his friends lol

I'm not stalking, I'm just looking around Github and following random people, because, well, I am a beginner and am just looking for code that I can read and try to understand. So a good place to start would be followers and all of people I know?

**Comment by cosmicle0** [comment]
> ood pla

alright, 😸
